user_endorsement_skills:
    path: /user/skills
    defaults: { _controller: "EndorsementBundle:Skill:index" }

user_endorsement_skills_add:
    path: /user/skills/add
    defaults: { _controller: "EndorsementBundle:Skill:add" }

user_endorsement_skills_remove:
    path: /user/skills/remove/{id}
    defaults: { _controller: "EndorsementBundle:Skill:remove" }

user_endorsement_endorse_user:
    path: /user/endorse/{id}
    defaults: { _controller: "EndorsementBundle:Skill:endorseUser" }

user_endorsement_skill_autocomplete:
    path:  /user/endorse/skill/autocomplete
    defaults: { _controller: EndorsementBundle:Skill:autoComplete }
    methods:  [GET]
