services:
  endorsement.endorsement_event_listener:
    class: OkulBilisim\EndorsementBundle\EventListener\EndorsementEventListener
    arguments: [@doctrine.orm.entity_manager, @router, @ojs.journal_service]
    tags:
      - { name: kernel.event_subscriber }
